In [1]:
#Associative & Commutative Properties in Linear Algebra
import numpy as np

In [5]:
#Dot product, number of columns in the first matrix must equal the number of rows in the second matrix
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[2], [4]])
C = np.dot(A,B) #Alternative method dot() C = A.dot(B)
C

array([[10],
       [22],
       [34]])

In [7]:
#Matrix multiplication, Dot product 4x3 dot 3x2 matrices = 4x2 matrix
A = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
B = np.array([[2, 7], [1, 2], [3, 6]])
C = A.dot(B)
C

array([[ 13,  29],
       [ 31,  74],
       [ 49, 119],
       [ 67, 164]])

In [11]:
#A*(B+C)
A = np.array([[2,3], [1,4], [7,6]])
B = np.array([[5], [2]])
C = np.array([[4], [3]])
D = A.dot(B+C)
D

array([[33],
       [29],
       [93]])

In [12]:
#A*B + A*C = A*(B+C)
D = A.dot(B) + A.dot(C)
D

array([[33],
       [29],
       [93]])

In [22]:
#Associative Property of Matrices
A = np.array([[2, 3], [1, 4], [7, 6]])
B = np.array([[5, 3], [2, 2]])
D = A.dot(B.dot(C))
print("A[B*C]: \n\n", D)
D = (A.dot(B)).dot(C)
print("\n [A*B]C: \n\n", D)

A[B*C]: 

 [[100]
 [ 85]
 [287]]

 [A*B]C: 

 [[100]
 [ 85]
 [287]]


In [74]:
#No commutative property in matrix algebra because columns[matrix 1] = rows[matrix 2]
A = np.array([[2,3], [6,5]])
B = np.array([[5, 3], [2, 2]])
AB = np.dot(A, B)
print("A*B: \n\n", AB, "\n\n")
BA = np.dot(B,A)

comm = AB==BA
if False in comm:
    print("Values are different: No commutative property exists in matrix algebra.")
    print("B*A: \n\n", BA)
    
else: 
    print("A*B=B*A, commutative property exists", AB==BA)

A*B: 

 [[16 12]
 [40 28]] 


Values are different: No commutative property exists in matrix algebra.
B*A: 

 [[28 30]
 [16 16]]


In [75]:
#No commutative property in matrix algebra because columns[matrix 1] = rows[matrix 2]
A = np.array([[2,3], [6,5], [1,1]])
B = np.array([[5, 3], [2, 2]])
AB = np.dot(A, B)
print("A*B: \n\n", AB, "\n\n")

try:
    BA = np.dot(B,A)
    print("B*A: \n\n", BA) ###Results in value error
except ValueError:
    print("B*A: \n\n columns[matrix 1] != rows[matrix 2]")

A*B: 

 [[16 12]
 [40 28]
 [ 7  5]] 


B*A: 

 columns[matrix 1] != rows[matrix 2]


In [93]:
#Commutative property in arrays: The transpose of x multiplied by y is equal to the transpose of y multiplied by x 
x = np.array([[2], [6]])
y = np.array([[5], [2]])

x_transpose = x.T.dot(y)
print("x_transpose*y:", int(x_transpose))

y_transpose = y.T.dot(x)
print("y_transpose*x:", int(y_transpose))

x_transpose*y: 22
y_transpose*x: 22


In [101]:
#The transpose of A*B is equal to the transpose of A multiplied by the transpose of B
A = np.array([[2, 3], [1, 4], [7, 6]])
B = np.array([[5, 3], [2, 2]])
AB_transpose = A.dot(B).T
B_tranA = B.T.dot(A.T)
print("The transpose of A*B: \n\n", B_tranA)
print("\n\n The transpose of A multiplied by the transpose of B: \n\n", AB_transpose)

The transpose of A*B: 

 [[16 13 47]
 [12 11 33]]


 The transpose of A multiplied by the transpose of B: 

 [[16 13 47]
 [12 11 33]]
