In [2]:
#Create Matrices and Vectors, Basics of Shapes, Nested Brackets
#Transpose Matrices with .T
#Add Matrices
#Broadcasting/Add two matrices of different shapes

import numpy as np

In [3]:
#Create a vector
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [5]:
#two-dimensional array with nested bracket
A = np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
#display the number of rows and columns with "shape"
A.shape

(3, 2)

In [7]:
#display the number of rows and columns with "shape"
x.shape

(4,)

In [8]:
#display the number of indices or units in x
len(x)

4

In [31]:
#Transpose matrix A
A = np.array([[1,2],[3,4],[5,6]])
print("Matrix A, untransposed: \n ", A)
transposed_A = A.T
print("\n", "Matrix A, transposed: \n ", A_t)

Matrix A, untransposed: 
  [[1 2]
 [3 4]
 [5 6]]

 Matrix A, transposed: 
  [[1 3 5]
 [2 4 6]]


In [33]:
#Shape
print(A.shape)
print(transposed_A.shape)

(3, 2)
(2, 3)


In [35]:
#Add two matrices together
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[2, 5], [7, 4], [4, 3]])
C = A + B
C

array([[ 3,  7],
       [10,  8],
       [ 9,  9]])

In [36]:
#Add a scalar to a matrix
C = A + 4
C

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [39]:
#Broadcasting: Add two matrices of different shapes
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[2], [4], [6]])
C=A+B
C

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])